### ISSUE TITLE
Update fluentd logdna plugin gem

### ISSUE THREAD

**Issue by AndrewChubatiuk** [logdna/fluent-plugin-logdna#11]
The latetst version(0.1.7) of fluentd logdna plugin was updated more than a year ago(April 20, 2017) but last updates were done 2 months ago, can you please keep fluentd logdna plugin gem up-to-date?

**Comment by mattcui** [comment]
@baronomasia Please help update to 0.1.7.1, this version supports to specify logdna server url, it's a very important feature. Thanks.

**Comment by peterbytes** [comment]
@AndrewChubatiuk @mattcui just a heads up, the gem is now up to date

**Comment by nvanheuverzwijn** [comment]
I think we can close this issue.
