### ISSUE TITLE
Socket getting stuck

### ISSUE THREAD

**Issue by kaleal** [logdna/fluent-plugin-logdna#25]
I have seen the socket getting stuck frequently these days. I notice that there is no timeout set on the persistent http call.

The httprb library doesn't set an implicit timeout and need to be set before sending requests.

Reference: https://github.com/httprb/http/wiki/Timeouts

https://github.com/logdna/fluent-plugin-logdna/blob/be7c4afc058d9dcd1e08ebfae335139a0fa30714/lib/fluent/plugin/out_logdna.rb#L82

**Comment by matt-march** [comment]
hello @kaleal, apologies for the delay. I believe there is a keep alive timeout set in the plugin setup. 

https://github.com/logdna/fluent-plugin-logdna/blob/be7c4afc058d9dcd1e08ebfae335139a0fa30714/lib/fluent/plugin/out_logdna.rb#L28

Were you referring to a different timeout?

**Comment by kaleal** [comment]
Hi Matt,

**keepalive** and **timeout** serve to different proposes.

Keepalive allows **reusing an active HTTP session** avoiding the overhead of opening and closing a new session each time the agent needs to send logs to logdna. Timeout, on the other hand, permits the agent to **give up waiting for any response from the server**.

On the line you had pointed out it is defined **keep_alive_timeout = 60** that means the session will still be opened for 60s after use. If 60s is passed with no use the session is expired and the socket is closed.

The issue that I have mentioned has nothing to do with HTTP session reuse. What is (actually was) happening was the socket waiting for server response forever and the current flush routine got stuck until the buffer get full.

For that issue the easiest way for fixing it would be adding the timeout method and specifying the global timeout value such as below:

@ingester.timeout(10).headers('apikey' => @api_key,

This way after 10s (your choice) with no server response a HTTP::TimeoutError is raised and the buffer flushing routine retries seconds later.

More details about timeouts go to https://github.com/httprb/http/wiki/Timeouts

**Comment by matt-march** [comment]
Thanks @kaleal, I misunderstood what you were saying. Let me try and figure out what an appropriate timeout would get and work up a PR.

**Comment by n5i** [comment]
What would be a proper way to reproduce the bug?

**Comment by smusali** [comment]
@godevk8s @kaleal the fix has already been released, thanks to @matt-march!
