### ISSUE TITLE
Add a new fluentd configuration parameter to let user specify an alternate endpoint

### ISSUE THREAD

**Issue by tapas-saha** [logdna/fluent-plugin-logdna#31]
As of now, the LogDNA plugin for `fluentd`, does not provide an option to specify an alternate endpoint for pushing the logs. The URL is hardcoded with `/logs/ingest` ([see here](https://github.com/logdna/fluent-plugin-logdna/blob/58952e79d7d6090e0b524f39750eb3006962e6d5/lib/fluent/plugin/out_logdna.rb#L100)), resulting in the logs always being pushed to the only one specific endpoint.

A new configuration parameter, within `fleuntd`'s configuration file, is needed to be introduced so that the user can override the default, i.e. `/logs/ingest`. This could be useful in many situations wherein pushing to the mentioned default endpoint may not be desired. This would also enable the LogDNA development team to expose many other alternate endpoints in the future, for whatever reasons; and the user can start consuming those according to their needs by overriding the default one.

**Comment by tapas-saha** [comment]
I myself will work on this.

**Comment by tapas-saha** [comment]
Created this [PR](https://github.com/logdna/fluent-plugin-logdna/pull/32). Review and merge awaited.

**Comment by tapas-saha** [comment]
The [PR](https://github.com/logdna/fluent-plugin-logdna/pull/32) was merged. Thanks to @matt-march @smusali @jakedipity for the reviews. Thanks to @smusali for the merge.

**Comment by tapas-saha** [comment]
@matt-march, @smusali looks like this change is not yet reflecting in the `gem` download server. How and when that will happen?

**Comment by smusali** [comment]
@tapas-saha this has just been released:
- https://github.com/logdna/fluent-plugin-logdna/releases/tag/v0.4.0
- https://rubygems.org/gems/fluent-plugin-logdna

Thanks for your contribution!
